### ISSUE TITLE
Unwanted error responses coming in springfox 2.8.0

### ISSUE THREAD

**Issue by harish0000** [springfox/springfox#2312]
I have used below configuration for @ApiResponses but when i checked the swagger info unwanted 403 and 404 error response are coming even though i haven't added.
**springfox-swagger2** : 2.8.0
**springfox-swagger-ui** : 2.8.0
```
@ApiResponses(value = {
	@ApiResponse(code = 401, message = "List of supported error codes:\r\n" + "- 40: Missing credentials\r\n"
					+ "- 41: Invalid credentials", response = Error.class),
	@ApiResponse(code = 400, message = "List of supported error codes:\r\n" + "- 25: Missing header\r\n"
					+ "- 26: Invalid header value", response = Error.class),
	@ApiResponse(code = 503, message = "List of supported error codes:\r\n"
					+ "- 5: The service is temporarily unavailable", response = Error.class),
	@ApiResponse(code = 500, message = "List of supported error codes:\r\n"
					+ "- 1: Internal error", response = Error.class) })
```
Method : Get operation
![image](https://user-images.githubusercontent.com/22025958/37648088-f4e6d396-2c53-11e8-8ed3-a5a6a6e7cabe.png)

**Comment by dilipkrish** [comment]
You can disable to default response codes in your docket

**Comment by harish0000** [comment]
@dilipkrish  thanks ,below one worked 
```

return new Docket(DocumentationType.SWAGGER_2)
            .useDefaultResponseMessages(false)
```

**Comment by jtviegas** [comment]
Still finding default codes in 2.8.0, for instance, with class level responses as a default for the included methods:

```
...
@RequestMapping(value = "/api/carriers")
@Api(tags = { "carriers" }, value = "API root for carrier related functions.")
@io.swagger.annotations.ApiResponses(value = {
    @ApiResponse(code = 400, message = "Invalid status value", response = void.class),
    @ApiResponse(code = 500, message = "Internal server error", response = void.class) })
...
```
and then additionally in the method:
```
...
  @RequestMapping(method = RequestMethod.POST)
  @ApiOperation(value = "Creates a new carrier", notes = "", response = void.class)
  @io.swagger.annotations.ApiResponses(value = {
      @ApiResponse(code = 201, message = "successful operation", response = void.class),
      @ApiResponse(code = 422, message = "validation failure", response = void.class),
      @ApiResponse(code = 409, message = "uniqueness violation", response = void.class) })
  public ResponseEntity<Void> postCarrier(
...
```
...also config is disabling default codes:
```
...
@Bean
  public Docket api() {
    return new Docket(DocumentationType.SWAGGER_2).securityContexts(securityContext()).useDefaultResponseMessages(false)
        .select().apis(RequestHandlerSelectors.any()).paths(PathSelectors.any()).build();
  }
...
```
...we should be seeing 201, 400, 409, 422 and  500, but we always also see the 200 there, for some reason:
![image](https://user-images.githubusercontent.com/3536754/40107298-c9f18dd4-58ef-11e8-8fc3-07cc7da2ef5a.png)

... are you also seeing this?

**Comment by dilipkrish** [comment]
Yeah this is a little annoying bug. There is no way to signal that 201 is the default response. Currently there isnt a good way to fix that.

**Comment by dilipkrish** [comment]
@jtviegas would you mind creating a new issue for that so we dont miss it when working on 3.0

**Comment by jtviegas** [comment]
done it, thank you

**Comment by Yan-Zhurich** [comment]
Hi, as temporary workaround for removing 200 status code from everywhere,
excepting GET methods, I found useful creating following component:
`@Component
public class OkStatusCodeFilteringPlugin implements OperationBuilderPlugin {

    @Override
    public void apply(OperationContext operationContext) {
        if(!operationContext.httpMethod().equals(HttpMethod.GET)) {
            operationContext
                    .operationBuilder()
                    .build()
                    .getResponseMessages()
                    .removeIf(responseMessage -> responseMessage.getCode() == HttpStatus.OK.value());
        }
    }

    @Override
    public boolean supports(DocumentationType documentationType) {
        return true;
    }
}`
It works for me, but guys could you probably name possible unwanted outcomes of such approach?

**Comment by manuelsantiengineering** [comment]
I had the same issue. Another issue I am seeing is with the examples in the @ApiResponse, these are not showing. I am using version 2.9.2

**Comment by manuelsantiengineering** [comment]
@ApiResponses({
        @ApiResponse(code = 200, message = "Success!"),
        @ApiResponse(code = 400, message = "The identifier does not exists."),
        @ApiResponse(code = 401, message = "Password and Username cannot be blank or invalid username and password. Access Json Web Token (JWT) is missing or invalid.",
        				examples = @Example(value = { 
        								@ExampleProperty(mediaType = "Example json", value = "{\"username\": \"Invalid Username\",\"password\": \"Invalid Password\"}" ),
        								@ExampleProperty(mediaType = "Example string", value = "Access Json Web Token (JWT) is missing or invalid." ) 
        							})),
        @ApiResponse(code = 500, message = "Unexpected error.")
    })

**Comment by AMF1107** [comment]
Was another issue opened after this was closed?  I am using `springfox-boot-starter:3.0.0` and `springfox-swagger-ui:3.0.0` and this issue still exists.

**Comment by piefel** [comment]
I can confirm the issue still exists with 3.0.0

**Comment by t0r0X** [comment]
> Was another issue opened after this was closed? I am using `springfox-boot-starter:3.0.0` and `springfox-swagger-ui:3.0.0` and this issue still exists.

@AMF1107 It was #2664, but that got closed too.
