### ISSUE TITLE
Swagger is not generating correct example xml if the same object is the nested object of different objects

### ISSUE THREAD

**Issue by MahithaC** [springfox/springfox#2393]
Hi,
Attached is the swagger json generated using swagger v2/apidocs.

I have two java pojos in which I am using the common object SwaggerSubModel.
I am expecting to be named as given in @XmlElement annotation but is defaulting to field name

Two issues:
1) When referrenced from multiple objects example has subModel as the element name
2) When referrenced from single object example has SwaggerSubModelTest as name from xmlType annotation.

Need help with fixing the above two issues

Example shown in Swagger Editor:

```
<?xml version="1.0" encoding="UTF-8"?>
<SwaggerXmlJson>
	<Country>string</Country>
	<DocumentName>string</DocumentName>
	<Language>string</Language>
	<subModel>
		<Test001>string</Test001>
		<Test002>2018-05-02T18:03:16.535Z</Test002>
	</subModel>
	<Url>string</Url>
</SwaggerXmlJson>
```

I am expecting the highlighted element **subModel** with SwaggerSubModelXmlJson as mentioned in below pojo:

```
@Getter
@Setter
@Accessors(chain = true)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "SwaggerSubModelTest")
@XmlType(name = "SwaggerSubModelTest", propOrder = {
        "test001",
        "test002"
})
public class SwaggerSubModel {
    @XmlElement(name = "Test001", required = true)
    @NotNull
    private String test001;

    @XmlElement(name = "Test002", required = true)
    @NotNull
    private Date test002;
}

```
Two objects referrencing SwaggerSubModel :

```
@Getter
@Setter
@Accessors(chain = true)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "Accounts")
public class SwaggerXml {

    @XmlElement(name = "Url", required = true)
    @NotNull
    protected String url;
    @XmlElement(name = "Country", required = true)
    @NotNull
    protected String country;
    @XmlElement(name = "Language", required = true)
    @NotNull
    protected String language;
    @XmlElement(name = "DocumentName", required = true)
    @NotNull
    protected String documentName;

    @XmlElement(name = "SwaggerSubModelTest")
    protected SwaggerSubModel subModel;
}
```
```
@Getter
@Setter
@Accessors(chain = true)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "SwaggerXmlJson")
@XmlType(propOrder = {
        "url",
        "country",
        "language",
        "documentName",
        "subModel"
})
public class SwaggerXmlJson {

    @XmlElement(name = "Url", required = true)
    @NotNull
    protected String url;
    @XmlElement(name = "Country", required = true)
    @NotNull
    protected String country;
    @XmlElement(name = "Language", required = true)
    @NotNull
    protected String language;
    @XmlElement(name = "DocumentName", required = true)
    @NotNull
    protected String documentName;

    @XmlElement(name = "SwaggerSubModelTestZZ")
    protected SwaggerSubModel subModel;
}
```

pom dependencies:
```
<!-- https://mvnrepository.com/artifact/io.springfox/springfox-swagger2 -->
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger2</artifactId>
            <version>2.8.0</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/io.springfox/springfox-bean-validators -->
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-bean-validators</artifactId>
            <version>2.8.0</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/io.swagger/swagger-core -->
        <dependency>
            <groupId>io.swagger</groupId>
            <artifactId>swagger-core</artifactId>
            <version>1.5.3</version>
        </dependency>
```

Please let me know if I am missing something here

Thanks
Mahitha

**Comment by dilipkrish** [comment]
@MahithaC have you tried 2.9.0 if it is any better?

**Comment by MahithaC** [comment]
Yes not all but most of the issues are fixed with 2.9.0 but I dont see the version available in maven central. When can we expect to have the version available in maven central?

**Comment by dilipkrish** [comment]
@MahithaC It is available in [jcenter](https://www.deps.co/guides/public-maven-repositories/#jcenter)

**Comment by dilipkrish** [comment]
@Mahitac could you report back with findings for 2.9.0

**Comment by sadanandshinde** [comment]
Hello @dilipkrish ,

I have the same issue, a nested object inside an object and the JAXB @XmlElement name is ignored while generating the request structure and defaulted to the object name.

I am using the latest version 2.9.0 but still facing the issue, any help or pointers are appreciated

Thank you,
