### ISSUE TITLE
Spring data rest exception

### ISSUE THREAD

**Issue by wenerme** [springfox/springfox#2462]
Please take the time to search the repository, if your question has already been asked or answered.

- [x] 2.9.0

What kind of issue is this?

 - [x] springfox data rest can not init with spring data rest 2.0.7

```
Caused by: java.lang.NoSuchMethodError: org.springframework.data.repository.support.Repositories.getRepositoryInformationFor(Ljava/lang/Class;)Lorg/springframework/data/repository/core/RepositoryInformation;
	at springfox.documentation.spring.data.rest.EntityServicesProvider.requestHandlers(EntityServicesProvider.java:81) ~[springfox-data-rest-2.9.0.jar:2.9.0]
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper$2.apply(DocumentationPluginsBootstrapper.java:138) ~[springfox-spring-web-2.9.0.jar:2.9.0]
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper$2.apply(DocumentationPluginsBootstrapper.java:135) ~[springfox-spring-web-2.9.0.jar:2.9.0]
	at com.google.common.collect.Iterators$7.transform(Iterators.java:750) ~[guava-20.0.jar:na]
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47) ~[guava-20.0.jar:na]
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47) ~[guava-20.0.jar:na]
	at com.google.common.collect.MultitransformedIterator.hasNext(MultitransformedIterator.java:52) ~[guava-20.0.jar:na]
	at com.google.common.collect.MultitransformedIterator.hasNext(MultitransformedIterator.java:50) ~[guava-20.0.jar:na]
	at com.google.common.collect.ImmutableCollection$Builder.addAll(ImmutableCollection.java:408) ~[guava-20.0.jar:na]
	at com.google.common.collect.ImmutableList$Builder.addAll(ImmutableList.java:699) ~[guava-20.0.jar:na]
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:256) ~[guava-20.0.jar:na]
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:209) ~[guava-20.0.jar:na]
	at com.google.common.collect.FluentIterable.toList(FluentIterable.java:614) ~[guava-20.0.jar:na]
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.defaultContextBuilder(DocumentationPluginsBootstrapper.java:109) ~[springfox-spring-web-2.9.0.jar:2.9.0]
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.buildContext(DocumentationPluginsBootstrapper.java:96) ~[springfox-spring-web-2.9.0.jar:2.9.0]
	at springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper.start(DocumentationPluginsBootstrapper.java:167) ~[springfox-spring-web-2.9.0.jar:2.9.0]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:181) ~[spring-context-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	... 19 common frames omitted
```

The method is 

```
public Optional<RepositoryInformation> getRepositoryInformationFor(Class<?> domainClass)
```

**Comment by dilipkrish** [comment]
This is a duplicate of (TBD). This is because you're using a pre-boot-2.0/spring 5.0 version of spring data rest.

**Comment by madorb** [comment]
@dilipkrish that's not correct. I believe that the original poster had a typo and meant SDR 3 not 2. 

I'm using spring boot `2.0.2.RELEASE`, which includes Spring Data Rest `3.0.6.RELEASE` which is the latest version and have this issue. 

Don't tell mr "hypermedia uber alles" gierke, but i was looking for a quick and dirty example and i simply took https://github.com/olivergierke/spring-restbucks and added in springfox, and it fails. 

You can check out: https://github.com/madorb/spring-restbucks

and see failure by running `mvn package`

**Comment by wenerme** [comment]
I fixed in my local and deployed to my local, need to
upgrade springDataRest to 3.0.7 and

```
---
a/springfox-data-rest/src/main/java/springfox/documentation/spring/data/rest/EntityContext.java
+++
b/springfox-data-rest/src/main/java/springfox/documentation/spring/data/rest/EntityContext.java
@@ -75,7 +75,7 @@ public class EntityContext {
     Object domainType = resource.getDomainType();
     Java8OptionalToGuavaOptionalConverter converter = new
Java8OptionalToGuavaOptionalConverter();
     Class actualDomainType = (Class)
converter.convert(domainType).orNull();
-    return entities.getPersistentEntity(actualDomainType);
+    return (PersistentEntity<?, ?>
)converter.convert(entities.getPersistentEntity(actualDomainType)).orNull();
   }

   public CrudMethods crudMethods() {
```


Ben <notifications@github.com>于2018年6月7日周四 下午10:38写道：

**Comment by dilipkrish** [comment]
@madorb Thanks for reproducing an issue, I'll take a look

> mr "hypermedia uber alles" gierke,

Also ☝️ 🤣. You could say Im in the same camp as him, despite maintaining this project. There is a happy medium where both camps can co-exist however, havent had time to work on it tho 😮

**Comment by dilipkrish** [comment]
@wenerme thanks for the tip

**Comment by PowerStat** [comment]
I still have this problem when using Spring Boot 2.1.9.RELEASE with spring-boot-starter-data-rest and springfox 2.9.2 - looks like springfox 2.9.2 is still bound to spring-data-commons 1.x instead of 2.x.
Also I have to exclude com.google.guava guava artefact, because it's to old for my other dependencies ...
Would be nice to have a 2.10.x release with actual dependencies.
