### ISSUE TITLE
Compatability of springfox-boot-starter:3.0.0-SNAPSHOT and springfox-swagger-ui:3.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by marcauberer** [springfox/springfox#3345]
Hey,
awesome lib!
I have a question:
I'm implementing the dependencies like this:
```xml
<dependency>
  <groupId>io.springfox</groupId>
  <artifactId>springfox-boot-starter</artifactId>
  <version>3.0.0-SNAPSHOT</version>
</dependency>
<dependency>
  <groupId>io.springfox</groupId>
  <artifactId>springfox-swagger-ui</artifactId>
  <version>3.0.0-SNAPSHOT</version>
</dependency>
```

I'm getting this result:
![Capture](https://user-images.githubusercontent.com/59527509/85801235-b88a0900-b742-11ea-9058-636d50be4cc9.PNG)

and following error messages in the browser console:
```
TypeError: Cannot read property 'url' of undefined
    at n.value (topbar.jsx:123)
    at n.R.t.render (root-injects.jsx:92)
    at s._renderValidatedComponentWithoutOwnerOrContext (ReactCompositeComponent.js:796)
    at s._renderValidatedComponent (ReactCompositeComponent.js:819)
    at s.performInitialMount (ReactCompositeComponent.js:359)
    at s.mountComponent (ReactCompositeComponent.js:255)
    at Object.mountComponent (ReactReconciler.js:43)
    at s.performInitialMount (ReactCompositeComponent.js:368)
    at s.mountComponent (ReactCompositeComponent.js:255)
    at Object.mountComponent (ReactReconciler.js:43)
R.t.render @ index.js:11
_renderValidatedComponentWithoutOwnerOrContext @ swagger-ui-bundle.js?v=3.0.0-SNAPSHOT:73
_renderValidatedComponent @ swagger-ui-bundle.js?v=3.0.0-SNAPSHOT:73
performInitialMount @ swagger-ui-bundle.js?v=3.0.0-SNAPSHOT:73
mountComponent @ swagger-ui-bundle.js?v=3.0.0-SNAPSHOT:73
mountComponent @ index.js:11
performInitialMount @ swagger-ui-bundle.js?v=3.0.0-SNAPSHOT:73
mountComponent @ swagger-ui-bundle.js?v=3.0.0-SNAPSHOT:73
mountComponent @ index.js:11
performInitialMount @ swagger-ui-bundle.js?v=3.0.0-SNAPSHOT:73
mountComponent @ swagger-ui-bundle.js?v=3.0.0-SNAPSHOT:73
mountComponent @ index.js:11
mountChildren @ swagger-ui-bundle.js?v=3.0.0-SNAPSHOT:73
_createInitialChildren @ swagger-ui-bundle.js?v=3.0.0-SNAPSHOT:73
mountComponent @ swagger-ui-bundle.js?v=3.0.0-SNAPSHOT:73
mountComponent @ index.js:11
performInitialMount @ swagger-ui-bundle.js?v=3.0.0-SNAPSHOT:73
mountComponent @ swagger-ui-bundle.js?v=3.0.0-SNAPSHOT:73
mountComponent @ index.js:11
performInitialMount @ swagger-ui-bundle.js?v=3.0.0-SNAPSHOT:73
mountComponent @ swagger-ui-bundle.js?v=3.0.0-SNAPSHOT:73
mountComponent @ index.js:11
performInitialMount @ swagger-ui-bundle.js?v=3.0.0-SNAPSHOT:73
mountComponent @ swagger-ui-bundle.js?v=3.0.0-SNAPSHOT:73
mountComponent @ index.js:11
performInitialMount @ swagger-ui-bundle.js?v=3.0.0-SNAPSHOT:73
mountComponent @ swagger-ui-bundle.js?v=3.0.0-SNAPSHOT:73
mountComponent @ index.js:11
performInitialMount @ swagger-ui-bundle.js?v=3.0.0-SNAPSHOT:73
mountComponent @ swagger-ui-bundle.js?v=3.0.0-SNAPSHOT:73
mountComponent @ index.js:11
performInitialMount @ swagger-ui-bundle.js?v=3.0.0-SNAPSHOT:73
mountComponent @ swagger-ui-bundle.js?v=3.0.0-SNAPSHOT:73
mountComponent @ index.js:11
performInitialMount @ swagger-ui-bundle.js?v=3.0.0-SNAPSHOT:73
mountComponent @ swagger-ui-bundle.js?v=3.0.0-SNAPSHOT:73
mountComponent @ index.js:11
performInitialMount @ swagger-ui-bundle.js?v=3.0.0-SNAPSHOT:73
mountComponent @ swagger-ui-bundle.js?v=3.0.0-SNAPSHOT:73
mountComponent @ index.js:11
performInitialMount @ swagger-ui-bundle.js?v=3.0.0-SNAPSHOT:73
mountComponent @ swagger-ui-bundle.js?v=3.0.0-SNAPSHOT:73
mountComponent @ index.js:11
performInitialMount @ swagger-ui-bundle.js?v=3.0.0-SNAPSHOT:73
mountComponent @ swagger-ui-bundle.js?v=3.0.0-SNAPSHOT:73
mountComponent @ index.js:11
C @ helpers.js:6
perform @ index.js:11
A @ helpers.js:6
perform @ index.js:11
batchedUpdates @ swagger-ui-bundle.js?v=3.0.0-SNAPSHOT:73
batchedUpdates @ swagger-ui-bundle.js?v=3.0.0-SNAPSHOT:6
_renderNewRootComponent @ helpers.js:6
_renderSubtreeIntoContainer @ helpers.js:6
render @ helpers.js:6
D @ index.js:11
h @ swagger-ui-bundle.js?v=3.0.0-SNAPSHOT:91
Qr @ swagger-ui-bundle.js?v=3.0.0-SNAPSHOT:91
n @ springfox.js?v=3.0.0-SNAPSHOT:1
(anonymous) @ springfox.js?v=3.0.0-SNAPSHOT:1
s @ swagger-ui-bundle.js?v=3.0.0-SNAPSHOT:73
(anonymous) @ swagger-ui-bundle.js?v=3.0.0-SNAPSHOT:73
forEach.e.<computed> @ swagger-ui-bundle.js?v=3.0.0-SNAPSHOT:73
v @ springfox.js?v=3.0.0-SNAPSHOT:1
u @ springfox.js?v=3.0.0-SNAPSHOT:1
Promise.then (async)
v @ springfox.js?v=3.0.0-SNAPSHOT:1
u @ springfox.js?v=3.0.0-SNAPSHOT:1
Promise.then (async)
v @ springfox.js?v=3.0.0-SNAPSHOT:1
u @ springfox.js?v=3.0.0-SNAPSHOT:1
Promise.then (async)
v @ springfox.js?v=3.0.0-SNAPSHOT:1
u @ springfox.js?v=3.0.0-SNAPSHOT:1
Promise.then (async)
v @ springfox.js?v=3.0.0-SNAPSHOT:1
u @ springfox.js?v=3.0.0-SNAPSHOT:1
Promise.then (async)
v @ springfox.js?v=3.0.0-SNAPSHOT:1
u @ springfox.js?v=3.0.0-SNAPSHOT:1
Promise.then (async)
v @ springfox.js?v=3.0.0-SNAPSHOT:1
u @ springfox.js?v=3.0.0-SNAPSHOT:1
(anonymous) @ springfox.js?v=3.0.0-SNAPSHOT:1
(anonymous) @ springfox.js?v=3.0.0-SNAPSHOT:1
(anonymous) @ springfox.js?v=3.0.0-SNAPSHOT:1
(anonymous) @ springfox.js?v=3.0.0-SNAPSHOT:1
s @ swagger-ui-bundle.js?v=3.0.0-SNAPSHOT:73
(anonymous) @ swagger-ui-bundle.js?v=3.0.0-SNAPSHOT:73
forEach.e.<computed> @ swagger-ui-bundle.js?v=3.0.0-SNAPSHOT:73
v @ springfox.js?v=3.0.0-SNAPSHOT:1
u @ springfox.js?v=3.0.0-SNAPSHOT:1
(anonymous) @ springfox.js?v=3.0.0-SNAPSHOT:1
(anonymous) @ springfox.js?v=3.0.0-SNAPSHOT:1
window.onload @ springfox.js?v=3.0.0-SNAPSHOT:1
load (async)
(anonymous) @ springfox.js?v=3.0.0-SNAPSHOT:1
r @ springfox.js?v=3.0.0-SNAPSHOT:1
(anonymous) @ springfox.js?v=3.0.0-SNAPSHOT:1
r @ springfox.js?v=3.0.0-SNAPSHOT:1
(anonymous) @ springfox.js?v=3.0.0-SNAPSHOT:1
(anonymous) @ springfox.js?v=3.0.0-SNAPSHOT:1
Show 35 more frames
root-injects.jsx:94 TypeError: Cannot read property 'url' of undefined
    at n.value (topbar.jsx:123)
    at n.R.t.render (root-injects.jsx:92)
    at s._renderValidatedComponentWithoutOwnerOrContext (ReactCompositeComponent.js:796)
    at s._renderValidatedComponent (ReactCompositeComponent.js:819)
    at s._updateRenderedComponent (ReactCompositeComponent.js:743)
    at s._performComponentUpdate (ReactCompositeComponent.js:721)
    at s.updateComponent (ReactCompositeComponent.js:642)
    at s.receiveComponent (ReactCompositeComponent.js:544)
    at Object.receiveComponent (ReactReconciler.js:122)
    at s._updateRenderedComponent (ReactCompositeComponent.js:751)
```

Is there something badly configured or is this a bug?

**Comment by dilipkrish** [comment]
You dont need the swagger-ui dependency any more. Try removing it. Also curl to your `<host>/<contextpath>/[v2|v3]/api-docs` and see if you can see the generated specs?

**Comment by marcauberer** [comment]
Ah ok. Did not know that the `swagger-ui` dependency.
The curl request returns a probably valid result for both of the specs. I don't know, why it does not work.

**Comment by desiderati** [comment]
Just to inform you guys. It's working as you have explained but if you set the context-path like this: server.servlet.context-path=/samples, the following error occurs. The UI is not taking into account the custom context path.

![image](https://user-images.githubusercontent.com/20958623/85899460-7b6e5700-b7d4-11ea-972b-0c60fc4168b3.png)

![image](https://user-images.githubusercontent.com/20958623/85899494-8d4ffa00-b7d4-11ea-9400-08c2fb8dc643.png)

**Comment by dilipkrish** [comment]
This should've been fixed via https://github.com/springfox/springfox/commit/8dff74823f9506c167a5c3e7446b61ec26b02a9f

**Comment by desiderati** [comment]
@dilipkrish Now the http://localhost:9090/swagger-ui.html is not working anymore, I was looking at the modification which you have posted before and I have percept that swagger-ui.html is not being mapped anymore. Is there a new place in which can I access it?
I have checked and the mapping available here in my sample application is this one:

![image](https://user-images.githubusercontent.com/20958623/85921057-7bf80380-b84f-11ea-85f3-de8878bc2e98.png)

Thanks.

**Comment by marcauberer** [comment]
I can confirm this. I only see an 404 error now

**Comment by dilipkrish** [comment]
@desiderati Thanks for that great suggestion! ill add that in there

**Comment by marcauberer** [comment]
Ok. But this does not solve my original problem. The error messages are still there and the website only shows `No API definition provided`.

**Comment by dilipkrish** [comment]
@marcauberer you're still using 2.10.5, which is different from this issue. Great project you have going BTW!

Here is something to try, while we're working to release 3.0.0 shortly

```xml
<!-- Remove this
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger2</artifactId>
			<version>2.9.2</version>
		</dependency>
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger-ui</artifactId>
			<version>2.10.5</version>
		</dependency>
-->
<!-- Add this dependency -->
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-boot-starter</artifactId>
			<version>3.0.0-SNAPSHOT</version>
		</dependency>
```

In your SwaggerConfig.kt
```java
//Remove 
@EnableSwagger2
  
//Change this  
    @Bean
    fun api() = Docket(DocumentationType.OAS_30) //<-- Change this
```

See if this works better for you and would love feedback.

**Comment by marcauberer** [comment]
@dilipkrish Thank you! It's working now. The solution was to change DocumentationType.SWAGGER_12 to DocumentationType.OAS_30. The rest of the required changes were already present in the regarding brach. Thanks for helping me! Closing this.

**Comment by sverhagen** [comment]
I can open a new issue, but it seemed appropriate to ask here, is there any way with 3.0.0 to get `/swagger-ui.html` to work again, or is `/swagger-ui/`(`index.html`) mandatory now? Thank you.

**Comment by dilipkrish** [comment]
@sverhagen that is mandatory now. Being always available at the root of the context as `swagger-ui.html` without any resource handler has always been problematic. May I ask what your use case is? One solution I can think of is

```java
    registry.addViewController(baseUrl + "/swagger-ui/swagger-ui.html")
        .setViewName("forward:" + baseUrl + "/swagger-ui/index.html");
```

But that would still have it like `/swagger-ui/swagger-ui.html` and also it would require a change in springfox.js to also expect `swagger-ui.html` when calcualting the base path.

**Comment by sverhagen** [comment]
Thank you for your answer, and in any case a big thank you anyway for the 3.0.0 coming out!!! I'm not sure what `registry` is, here, but regardless, I already created a temporary redirect (will make it permanent in the foreseeable future) using a `RouterFunction`. I'm able to include query parameters in the redirect (we have some customizations that rely on query parameters), so I think that for all practical matters we're good. But we have been telling our users that API documentation can be found at `/swagger-ui.html` and this now also exists in a bunch of other communications, so I didn't want to take changing that too lightly (but I will move on now).
