### ISSUE TITLE
Cycles in Java classes cause infinite loop in ModelAttributeParameterExpander

### ISSUE THREAD

**Issue by candrews** [springfox/springfox#621]
When using JPA, Hibernate, and other ORMs, it's common for each side of a relationship to refer to the other. For example:
```Java
class Person {
	private String firstName;
	private String lastName;
	private Address address;

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}
	public Address getAddress() {
		return address;
	}

	public void setAddress(Address address) {
		this.address= address;
	}
}

class Address {
	private String street;
	@ApiModelProperty(hidden = true)
	private Person person;

	public String getStreet() {
		return street;
	}

	public void setStreet(String street) {
		this.street = street;
	}
	public Person getPerson() {
		return person;
	}

	public void setPerson(person person) {
		this.person= person;
	}
}
```
Currently, this set of classes causes an infinite loop resulting in a StackOverflowError in com.mangofactory.swagger.readers.operation.parameter.ModelAttributeParameterExpander.expand(String, Class<?>, List<Parameter>). The problem is that the Java classes are expanded but the annotation which would cause the field to be excluded is being processed, so Person references Address references Person... and the expansion continues infinitely.

I think the solution is to simply process @ApiModelProperty(hidden = true) annotations at expansion time. It may also be nice to detect when such cycles occur and throw a descriptive error (instead of getting a StackOverflowError) but that's just a nice to have... solving the problem would quite sufficient :-)

Thanks!

**Comment by dilipkrish** [comment]
@candrews I suspect this may be a bug. Will take a look, but most likely its going to be fixed in 2.x

**Comment by candrews** [comment]
The team here and I are very psyched about using Swagger, and this issue is a blocker for us, so I have to ask - what's the timeline for 2.x?

Also, my naive impression is that if a check for the @ApiModel(hidden=true) annotation on the "field" variable in the "expand" method would solve this problem and doesn't seem like it could cause regressions, so is that solution workable, and would it be permitted in a near future non-2.x release?

**Comment by dilipkrish** [comment]
Well its really close :) but i'll say at least 2 weeks before a public snapshot/release. Let me see if I can fix it in 1.0.2.

**Comment by dilipkrish** [comment]
Having said that, I'd say a couple things

- the new 2.0 the api will have changed a little bit (as regards ```SwaggerSpringMvcPlugin``` and is set up to support multiple service description formats, swagger 1.2 and swagger 2.0 are supported out of the box, with plans to support more formats on the way.
- secondly all the swagger annotations will be supported across both those versions.

**Comment by adrianbk** [comment]
we shouldn't rely on an annotation as a means to break the cycle.

**Comment by dilipkrish** [comment]
@candrews Out of curiosity why are these deep domain objects annotated with ```@ModelAttribute```?

**Comment by candrews** [comment]
I'm using them in controller methods, ex:
```java
@Controller
public class AddressService {
   	@Autowired
	private AddressService addressService;

	@ModelAttribute("address")
	public Address getAddress(@PathVariable int addressId) {
		return addressService.getById(addressId);
	}

	@RequestMapping(value = "/address/{addressId}", method = RequestMethod.POST)
	@ResponseBody
	public Address updateById(@PathVariable int addressId,
			@Valid @ModelAttribute("address") Address address) {
		return addressService.update(degree);
	}
}
```

There are a lot more methods (getting, updating, deleting, then using views/templates for html rendering, etc) but that's the basic idea. I think that's a pretty common approach. (Using view objects distinct from the entities seems to be a common alternative, but this pattern seems to work fine, too.)

**Comment by dilipkrish** [comment]
@candrews It seems like its a lot harder to fix it that I had anticipated in 1.x, especially since I suspect you're expecting that ```Person``` is ignored in the ```Address``` object. Its a little simpler in 2.0 work we've been doing. 

Unfortunately, I think it makes more sense for use to focus our efforts on getting 2.x out.

**Comment by dilipkrish** [comment]
This should now be fixed in 2.0

**Comment by cm325** [comment]
This doesn't appear to be fixed, I tried versions 2.0.1 - 2.1.1, the only versions I could try before the need for spring 4. I have the same setup, where entities reference one another, I applied the @ApiModelProperty(hidden = true) but I still get an endless stream of :

2016-01-08 12:47:52,601 [localhost-startStop-1] DEBUG springfox.documentation.spring.web.readers.parameter.ModelAttributeParameterExpander- Attempting to expand expandable field:
2016-01-08 12:47:52,601 [localhost-startStop-1] DEBUG springfox.documentation.spring.web.readers.parameter.ModelAttributeParameterExpander- Expanding parameter type:

ending in stackoverflow here:

springfox.documentation.spring.web.readers.parameter.ModelAttributeParameterExpander.expand(ModelAttributeParameterExpander.java:84)

**Comment by dilipkrish** [comment]
@cm325 could you please try with 2.3.1 that is spring 3 compatible again

**Comment by dilipkrish** [comment]
If not please open a :bug:

**Comment by cm325** [comment]
Hi, yes, sry, I just edited my comment to include the fact that I just saw that 2.3.1 is spring 3 compatible, and just tested with that as well, and unfortunately, the same error occurs. I will open new bug-

**Comment by dilipkrish** [comment]
👍🏼 would be useful if u can provide a failing model or better still a
failing test.

**Comment by cm325** [comment]
I just posted this - 

https://github.com/springfox/springfox/issues/1133

hoping that will be enough-

**Comment by yangshimeng** [comment]
help me .
