### ISSUE TITLE
Groovy metaClass not ignored when model is built for deserialization

### ISSUE THREAD

**Issue by aleksz** [springfox/springfox#752]
```
	@RequestMapping(value = "/myresource", method = RequestMethod.GET)
	MyResource get() {
	}

	@RequestMapping(value = "/myresource", method = RequestMethod.POST)
	MyResource save(@Valid @RequestBody MyResource myResource) {
	}
```
When I have only "get", in my controller - MyResource does not have metaClass. As soon as I add "save", metaClass appears in both calls.

swagger-annotations:1.5.3-M1
swagger-model:1.5.3-M1
springfox-swagger2:2.0.0
jackson:2.4.5

Tracked to this code in BeanModelPropertyProvider:
```
  private BeanDescription beanDescription(ResolvedType type, ModelContext context) {
    if (context.isReturnType()) {
      SerializationConfig serializationConfig = objectMapper.getSerializationConfig();
      return serializationConfig.introspect(TypeFactory.defaultInstance()
          .constructType(type.getErasedType()));
    } else {
      DeserializationConfig serializationConfig = objectMapper.getDeserializationConfig();
      return serializationConfig.introspect(TypeFactory.defaultInstance()
          .constructType(type.getErasedType()));
    }
  }
```
In both cases introspect returns metaClass description

**Comment by dilipkrish** [comment]
You should probably apply a mix in to all your groovy models with the `@JsonIgnoredProperties(["metaClass"]` annotation.

**Comment by aleksz** [comment]
This does not help

**Comment by dilipkrish** [comment]
Weird. Do you have an example repo? Another thing u could try is to add the groovy `Metaclass` To the ignorable types in your `Docket`  If nothing works feel free to reopen this issue.

**Comment by aleksz** [comment]
Do you mean Docket.ignoredParameterTypes. It says:
```
   * Adds ignored controller method parameter types so that the framework does not generate swagger model or parameter
   * information for these specific types.
   * e.g. HttpServletRequest/HttpServletResponse which are already included in the pre-configured ignored types.
```

Should there be something else?

**Comment by dilipkrish** [comment]
Yes, u can add the groovy Metaclass to the ignorables using that method.

**Comment by aleksz** [comment]
I think this method does what JavaDoc says, ignores parameter types, not
properties with that type :) OperationParameterReader.readParameters seems
to be the place. Sorry if i miss something.

**Comment by aleksz** [comment]
Tried one more thing:
```
	@JsonIgnoreType
	class IgnoreTypeMixIn {
		//
	}

	@Bean
	public Jackson2ObjectMapperBuilder jacksonBuilder() {
		Jackson2ObjectMapperBuilder builder = new Jackson2ObjectMapperBuilder()
		builder.mixIn(MetaClass, IgnoreTypeMixIn)
		return builder
	}
```

still same effect. Also changing MetaClass to String affects serialized properties, but not Swagger documentation.

**Comment by dilipkrish** [comment]
I've added tests that demonstrate there is no issue in the library as-is. I suspect you've customized your ObjectMapper which in turn is causing the groovy meta class to show

**Comment by aleksz** [comment]
it seems to me that this test does not test problematic case. I'm having issue with de-serialization, so you need to use that Groovy model as request body, not response.

**Comment by aleksz** [comment]
I think I know why global mix in has no effect. Spring Boot has multiple MappingJackson2HttpMessageConverter converters. One is default, registered by AllEncompassingFormHttpMessageConverter. Another one is added by JacksonAutoConfiguration. As a result, FieldModelPropertyProvider.onApplicationEvent is called multiple times and last wins. Unfortunately, this is not the one from JacksonAutoConfiguration. Maybe ObjectMapperConfigurer should handle only primary one?

**Comment by dilipkrish** [comment]
Thanks for pursuing the issue. This should now be fixed

**Comment by aleksz** [comment]
Thanks for fixing. Any plans to release it soon?

**Comment by dilipkrish** [comment]
Hopefully end of this week

**Comment by aleksz** [comment]
Verified that ignoredParameterTypes(MetaClass) does the job. However, there is still an issue with picking wrong ObjectMapper, which I believe is the root cause. Any mix ins or other configuration applied to correct ObjectMapper will be ignored.

**Comment by dilipkrish** [comment]
@aleksz have you used the guidance in the docs [to configure the ObjectMapper](http://springfox.github.io/springfox/docs/current/#configuring-the-objectmapper)? If you do it that way or create ObjectMapper using the [Jackson2ObjectMapperBuilder](http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/http/converter/json/Jackson2ObjectMapperBuilder.html) you shouldn't run into that issue.

**Comment by zhangfei9734** [comment]
docket.ignoredParameterTypes(groovy.lang.MetaClass.class)
